CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nickname" varchar UNIQUE NOT NULL,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "birthday" date NOT NULL DEFAULT '2000-01-01',
  "age" varchar DEFAULT 10,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "phone" varchar
);

CREATE TABLE "teachers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "birthday" date NOT NULL DEFAULT '2000-01-01',
  "age" varchar DEFAULT 18,
  "email" varchar UNIQUE,
  "phone" varchar
);

CREATE TABLE "user_course" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" int NOT NULL,
  "user_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text NOT NULL,
  "level_id" int NOT NULL,
  "teacher_id" int NOT NULL
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text NOT NULL,
  "url" varchar NOT NULL,
  "id_course" int NOT NULL
);

CREATE TABLE "course_category" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" int NOT NULL,
  "category_id" int NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text NOT NULL
);

CREATE TABLE "levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar NOT NULL
);

ALTER TABLE "course_video" ADD FOREIGN KEY ("id_course") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id") REFERENCES "levels" ("id");

ALTER TABLE "course_category" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "course_category" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "teachers" ("id");

ALTER TABLE "user_course" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_course" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

INSERT INTO teachers
(first_name, last_name, birthday, age, email, phone)
VALUES('Jesus', 'Fernandez', '1992-01-01'::date, 28, 'jesus@academlo.com', '+52 1 833 555 55555');

INSERT INTO levels
("name", description)
VALUES('Beginner',''),
('Intermediate',''),
('Advanced','');

INSERT INTO categories
(title, description)
VALUES('Web Development Basics',''),
('Front End with React','');

INSERT INTO users
(nickname, first_name, last_name, birthday, age, email, "password", phone)
VALUES
('dash', 'david', 'pedroza', '2000-02-21'::date, 23, 'david@gmail.com', 'admin123', '+57 3007265746');
('mari', 'maria', 'pedroza', '1998-03-11'::date, 25, 'mpedroza354@gmail.com', 'maria123', '57 3043819812'),
('juan', 'juan', 'contreras', '1997-11-11'::date, 26, 'jccp1111@hotmail.com', 'juan123', '57 3008911321');


INSERT INTO courses
(title, description, level_id, teacher_id)
VALUES('HTML + CSS + JavaScript','', 1, 1),
('React.js: Crash Course','', 1, 1);

INSERT INTO course_category
(course_id, category_id)
VALUES(1, 1),
(2, 2);

INSERT INTO course_video
(title, description, url, id_course)
VALUES('Introduction','','', 1),
('Introduction','', 'academlo.com/react/introduction', 2);

